--!strict

local ServerScriptService = game:GetService("ServerScriptService")

local Services = ServerScriptService:WaitForChild("Services")
local PlayerDataService = require(Services:WaitForChild("PlayerDataService"))
local InteractionService = require(Services:WaitForChild("InteractionService"))
local InventoryService = require(Services:WaitForChild("InventoryService"))
local LootService = require(Services:WaitForChild("LootService"))
local ExtractionService = require(Services:WaitForChild("ExtractionService"))
local RoundService = require(Services:WaitForChild("RoundService"))
local SecurityService = require(Services:WaitForChild("SecurityService"))
local GuardService = require(Services:WaitForChild("GuardService"))
local PoliceService = require(Services:WaitForChild("PoliceService"))
local PoliceAIService = require(Services:WaitForChild("PoliceAIService"))
local EscapeService = require(Services:WaitForChild("EscapeService"))
local DropBagService = require(Services:WaitForChild("DropBagService"))
local ArrestService = require(Services:WaitForChild("ArrestService"))

PlayerDataService.Start()
InventoryService.Start()
LootService.Start()
ExtractionService.Start()
RoundService.Start()
SecurityService.Start()
GuardService.Start()
PoliceService.Start()
PoliceAIService.Start()
EscapeService.Start()
DropBagService.Start()
ArrestService.Start()

print("[BlackwoodHeist] Foundation booted.")
