--!strict

export type ItemDefinition = {
	Id: string,
	Name: string,
	Category: string,
	BaseValue: number,
	Weight: number,
	Size: string,
	Rarity: string,
	CarryType: string,
	SpawnWeight: number,
	RequiredTool: string?,
}

local Items: { [string]: ItemDefinition } = {
	Smartphone = {
		Id = "Smartphone",
		Name = "Luxury Smartphone",
		Category = "Electronics",
		BaseValue = 900,
		Weight = 0.4,
		Size = "Small",
		Rarity = "Common",
		CarryType = "Small",
		SpawnWeight = 5,
	},
	Laptop = {
		Id = "Laptop",
		Name = "Encrypted Laptop",
		Category = "Electronics",
		BaseValue = 2400,
		Weight = 2.2,
		Size = "Small",
		Rarity = "Uncommon",
		CarryType = "Small",
		SpawnWeight = 4,
	},
	Watch = {
		Id = "Watch",
		Name = "Blackwood Chronograph",
		Category = "Jewelry",
		BaseValue = 3800,
		Weight = 0.3,
		Size = "Small",
		Rarity = "Rare",
		CarryType = "Small",
		SpawnWeight = 3,
	},
	CashBundle = {
		Id = "CashBundle",
		Name = "Cash Bundle",
		Category = "Cash",
		BaseValue = 1500,
		Weight = 1.0,
		Size = "Small",
		Rarity = "Common",
		CarryType = "Small",
		SpawnWeight = 5,
	},
	Painting = {
		Id = "Painting",
		Name = "Blackwood Landscape",
		Category = "Art",
		BaseValue = 6500,
		Weight = 8,
		Size = "Large",
		Rarity = "Rare",
		CarryType = "Large",
		SpawnWeight = 2,
	},
	Sculpture = {
		Id = "Sculpture",
		Name = "Marble Falcon Sculpture",
		Category = "Art",
		BaseValue = 9200,
		Weight = 12,
		Size = "Large",
		Rarity = "Epic",
		CarryType = "Large",
		SpawnWeight = 1,
	},
	ConfidentialDocument = {
		Id = "ConfidentialDocument",
		Name = "Confidential Dossier",
		Category = "Documents",
		BaseValue = 5200,
		Weight = 0.2,
		Size = "Small",
		Rarity = "Rare",
		CarryType = "Small",
		SpawnWeight = 2,
	},
}

return table.freeze(Items)
